most of the things are working

diff --git a/tip-wlan/charts/wlan-prov-service/templates/deployment.yaml b/tip-wlan/charts/wlan-prov-service/templates/deployment.yaml
--- a/tip-wlan/charts/wlan-prov-service/templates/deployment.yaml
+++ b/tip-wlan/charts/wlan-prov-service/templates/deployment.yaml
@@ -1,11 +1,10 @@
 {{- $pg := include "postgresql.service" . -}}
-{{- $ns := include "common.namespace" . -}}
 {{- $cloudeployment := .Values.global.isCloudDeployment -}}
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: {{ include "common.fullname" . }}
-  namespace: {{ include "common.namespace" . }}
+  namespace: {{ .Release.Namespace }}
   labels:
     {{- include "common.labels" . | nindent 4 }}
 spec:
@@ -19,11 +18,15 @@ spec:
         {{- include "common.selectorLabels" . | nindent 8 }}
     spec:
       imagePullSecrets:
-        - name: "{{ include "common.namespace" . }}-docker-registry-key"
+        - name: "{{ .Release.Namespace }}-docker-registry-key"
       serviceAccountName: {{ include "common.serviceAccountName" . }}
       securityContext:
         {{- toYaml .Values.podSecurityContext | nindent 8 }}
       initContainers:
+        - name: {{ include "common.name" . }}-readiness
+          image: busybox:1.28
+          imagePullPolicy: {{ .Values.global.pullPolicy }}
+          command: ['sh', '-c', "until nslookup {{ $pg }}.{{ .Release.Namespace }}.svc.cluster.local; do echo waiting for POSTGRES; sleep 2; done"]
         - name: {{ include "common.name" . }}-create-db-schema
           env:
           - name: POSTGRESQL_PORT_NUMBER
@@ -31,22 +34,22 @@ spec:
           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
-                name: {{ include "common.resource.name" . }}-credentials
+                name: {{ include "common.fullname" . }}-creds
                 key: postgresql-password
           - name: TIPUSER_PASSWORD
             valueFrom:
               secretKeyRef:
-                name: {{ include "common.resource.name" . }}-credentials
+                name: {{ include "common.fullname" . }}-creds
                 key: tipuser-password
           - name: SCHEMA_REPO_USER
             valueFrom:
               secretKeyRef:
-                name: {{ include "common.resource.name" . }}-credentials
+                name: {{ include "common.fullname" . }}-creds
                 key: schema-repo-user
           - name: SCHEMA_REPO_PASSWORD
             valueFrom:
               secretKeyRef:
-                name: {{ include "common.resource.name" . }}-credentials
+                name: {{ include "common.fullname" . }}-creds
                 key: schema-repo-password
           image: postgres:latest
           imagePullPolicy: IfNotPresent
@@ -69,9 +72,13 @@ spec:
             curl --insecure -u$SCHEMA_REPO_USER:$SCHEMA_REPO_PASSWORD -O "https://tip-tip-wlan-cloud-docker-repo.jfrog.io/artifactory/tip-wlan-cloud-schemas/0.0.1-SNAPSHOT/sql/cloud-sdk-schema-postgresql-db-user.sql"
             curl --insecure -u$SCHEMA_REPO_USER:$SCHEMA_REPO_PASSWORD -O "https://tip-tip-wlan-cloud-docker-repo.jfrog.io/artifactory/tip-wlan-cloud-schemas/0.0.1-SNAPSHOT/sql/cloud-sdk-schema-postgresql-tables.sql"
             echo "***** Now executing cloud-sdk-schema-postgresql-db-user.sql on host {{ $pg }} and creating db prov_db and user tip_user using User Postgres. This uses full client-cert authentication *****"
-            status=1
+            ### Observed that PSQL was unable to resolve the Postgres-service host because the postgres service wasnt 
+            ### really ready when running Postgres in Master-Slave config... hence the below retry-logic
+            psql 'host={{ $pg }} port=5432 user=postgres sslmode=verify-ca sslcert=/opt/tip-wlan/certs/postgresclientcert.pem sslkey=/opt/tip-wlan/certs/postgresclientkey_dec.pem sslrootcert=/opt/tip-wlan/certs/cacert.pem' -f cloud-sdk-schema-postgresql-db-user.sql
+            status=$(echo $?)
+            echo psql response of the request = $status
             counter=0
-            while [ $counter -lt 5 ] && [ $status -ne 0 ]
+            while [ $counter -lt 3 ] && [ $status -ne 0 ]
             do
               echo {{ $pg }} service isnt ready. Tried $counter times
               sleep 2
@@ -119,7 +126,11 @@ spec:
         - name: {{ .Chart.Name }}
           securityContext:
             {{- toYaml .Values.securityContext | nindent 12 }}
+          {{- if .Values.global.testingEnabled }}
+          image: {{ .Values.global.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}-{{.Values.global.testingTimestamp}}
+          {{- else }}
           image: {{ .Values.global.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
+          {{- end }}
           imagePullPolicy: {{ .Values.global.pullPolicy }}
           env:
             {{- include "common.env" . | nindent 12 }}
@@ -199,7 +210,7 @@ spec:
       volumes:
       - name: certificates
         secret:
-          secretName: {{ include "common.resource.name" . }}-postgres-client-certs
+          secretName: {{ include "common.fullname" . }}-certs
           defaultMode: 0400
       - name: logback-config
         configMap:
